version: '3.3'

services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: backend
    volumes:
      - ./Backend:/app
    ports:
      - "5000:5000"
    networks:
      - store-network
    environment:
      - DATABASE_URL=sqlite:////app/games.db

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3001:80"
    networks:
      - store-network
    depends_on:
      - backend

networks:
  store-network:
    driver: bridge