version: '3.3'

services:
  frontend:
    build:
      context: ./Frontend
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  backend:
    build:
      context: ./Backend
    ports:
      - "5001:5000"
    environment:
      - DATABASE_URL=sqlite:///games.db
    volumes:
      - ./Backend:/app
