version: '3.3'

services:
  backend:
    build:
      context: ./Backend
    container_name: backend
    volumes:
      - ./Backend/games.db:/app/games.db
    ports:
      - "5000:5000"
    networks:
      - app-network
    environment:
      - FLASK_ENV=development

  frontend:
    build:
      context: ./Frontend
    container_name: frontend
    ports:
      - "3001:3000"
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge
