apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-backend
  labels:
    app: flask-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-backend
  template:
    metadata:
      labels:
        app: flask-backend
    spec:
      containers:
        - name: flask-backend
          image: boti95/store-backend:latest
          ports:
            - containerPort: 5000
          env:
            - name: DATABASE_URL
              value: "sqlite:///games.db"
          volumeMounts:
            - name: flask-storage
              mountPath: /app/games.db
      volumes:
        - name: flask-storage
          emptyDir: {}
