apiVersion: v1
kind: Service
metadata:
  name: flask-backend-service
  labels:
    app: flask-backend
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 5000
  selector:
    app: flask-backend
