apiVersion: v1
kind: Service
metadata:
  name: node-frontend-service
  labels:
    app: node-frontend
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000 
  selector:
    app: node-frontend
