apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-frontend
  labels:
    app: node-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-frontend
  template:
    metadata:
      labels:
        app: node-frontend
    spec:
      containers:
        - name: node-frontend
          image: boti95/store-frontend:latest
          ports:
            - containerPort: 3000 
          env:
            - name: NODE_ENV
              value: "production"
